### ISSUE TITLE
Defining own keywords

### ISSUE THREAD

**Issue by mmattel** [lask79/antora-shiki-extension#1]
Reading about your extensions in the Antora Zulip channel - great 👍 

One question:
Is it possible to define own keywords taht get additionally be highlighted - I have nothing found in the readme about this.

We have "customized" highlight.js in our docs env to add a list of keywords that are normally not part of hljs.
Your extensions sounds realy great but defining additionally own keywords would be a requirement for us.

**Comment by lask79** [comment]
Hi @mmattel,
sorry for my late reply. In general it should be possible to add your own keywords by overriding/changing the existing language definition files (https://github.com/shikijs/shiki/tree/main/packages/shiki/languages).
What I could implement is a way to override an existing language by registering a local language file. Is this what you are looking for?

**Comment by mmattel** [comment]
For clarification, would that mean I have to copy the exising one and add stuff (replacement) or "just" make a new one and define what I would like to extend?

**Comment by lask79** [comment]
I added the feature in the new release 1.0.0-alpha.6. 

You can now define your own language by adding this to extension configuration:
```
register_languages:
  - id: 'xml'
    scope_name: 'text.xml'
    grammar_path: ./additional-languages/xml.tmLanguage.json
    # aliases: ['xml']
```

Please try this out and let me know if that is working for you. See more details in the README.

**Comment by mmattel** [comment]
Will do, but I caught a flu, so it will take a bit.

**Comment by lask79** [comment]
@mmattel: Did you have the chance to test this?

**Comment by lask79** [comment]
I will close the for now because there is a solution within the 1.0.0-alpha.6 version.
